---
language: "python"
python:
  - "3.7"

install:
  - "pip install -r requirements.txt"

before_script:
  - "yamllint -s *.yml"
  - "echo 'ansible' >> ~/vault_pass_file.txt"

script:
  - "ansible-playbook test.yml"
