---
all:
  hosts:
    ios-xe-mgmt.cisco.com:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_port: 8181
    ansible_user: root
    ansible_ssh_pass: D_Vay!_10&
    ntp_server1: 192.0.2.1
    ntp_server2: 192.0.2.2
...
