---
all:
  children:
    my_aws_csrs:
      hosts:
        34.203.128.131:
        34.225.32.188:
      vars:
        ansible_user: wade
        ansible_ssh_pass: fsa7yaof
    devnet_csr:
      hosts:
        ios-xe-mgmt.cisco.com:
      vars:
        ansible_port: 8181
        ansible_user: root
        ansible_ssh_pass: D_Vay!_10&
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ntp_server1: 192.0.2.1
    ntp_server2: 192.0.2.2
...
